backend:
  name: git-gateway
  branch: master

media_folder: public/images
public_folder: /images

collections:
  - name: "page"
    label: "Page"
    folder: "content/pages"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Category", name: "category", widget: "list" }
      - { label: "Content", name: "body", widget: "markdown", required: true }
